// OpenSage.SimCore.TableGen — emits FixTrig.Tables.g.cs, the checked-in LUT artifact of
// record for FixTrig (design-simcore-scaffolding §1.4, api-freeze-v1 F2).
//
// This tool runs at DEVELOPMENT time only and is therefore allowed to use System.Math:
// the generated raw longs are checked in, so the shipped game never depends on any
// platform's libm. FixTrigTests spot-checks the checked-in entries against independently
// computed constants, so regenerating on a machine with a divergent libm cannot silently
// drift the table.
//
// Usage: dotnet run --project src/tools/OpenSage.SimCore.TableGen [output-path]
//        (default output: src/OpenSage.SimCore/Numerics/FixTrig.Tables.g.cs relative to
//        the repository root, located by walking up from the current directory)

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

const string GeneratorVersion = "1.0";
const int SinTableBits = 14;
const int SinTableSize = 1 << SinTableBits;   // 16,384 entries over [0, π/2)
const int AtanTableSteps = 1024;              // 1,025 entries over ratio [0, 1]
const double One = 4294967296.0;              // 2^32

var outputPath = args.Length > 0 ? args[0] : FindDefaultOutputPath();

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine($"// Generated by OpenSage.SimCore.TableGen v{GeneratorVersion}.");
sb.AppendLine($"// Parameters: sinTableSize={SinTableSize} (quarter-symmetric, entry i = round(sin((PI/2)*i/{SinTableSize}) * 2^32)),");
sb.AppendLine($"//             atanTableSteps={AtanTableSteps} (entry i = round(atan(i/{AtanTableSteps}) * 2^32), {AtanTableSteps + 1} entries).");
sb.AppendLine("// Checked-in artifact of record (design-simcore-scaffolding §1.4): do not edit by hand;");
sb.AppendLine("// regenerate with this tool and let FixTrigTests verify the spot-check constants.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("namespace OpenSage.SimCore.Numerics");
sb.AppendLine("{");
sb.AppendLine("    public static partial class FixTrig");
sb.AppendLine("    {");

EmitTable(sb, "SinTable", Enumerable.Range(0, SinTableSize)
    .Select(i => (long)Math.Round(Math.Sin(Math.PI / 2 * i / SinTableSize) * One)));

sb.AppendLine();

EmitTable(sb, "AtanTable", Enumerable.Range(0, AtanTableSteps + 1)
    .Select(i => (long)Math.Round(Math.Atan((double)i / AtanTableSteps) * One)));

sb.AppendLine("    }");
sb.AppendLine("}");

File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"Wrote {outputPath}");

static void EmitTable(StringBuilder sb, string name, IEnumerable<long> values)
{
    sb.AppendLine($"        internal static readonly long[] {name} =");
    sb.AppendLine("        {");
    var column = 0;
    sb.Append("            ");
    foreach (var v in values)
    {
        sb.Append("0x").Append(v.ToString("X")).Append("L, ");
        if (++column % 8 == 0)
        {
            sb.AppendLine();
            sb.Append("            ");
        }
    }
    sb.AppendLine();
    sb.AppendLine("        };");
}

static string FindDefaultOutputPath()
{
    var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (dir != null)
    {
        var candidate = Path.Combine(dir.FullName, "src", "OpenSage.SimCore", "Numerics");
        if (Directory.Exists(candidate))
        {
            return Path.Combine(candidate, "FixTrig.Tables.g.cs");
        }
        dir = dir.Parent;
    }
    throw new InvalidOperationException(
        "Could not locate src/OpenSage.SimCore/Numerics above the current directory; pass an explicit output path.");
}
